name: "Code Quality"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  quality-flake8:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install mypy
          pip install flake8

      - name: Run flake8
        run: flake8 --ignore=E501,F401,F403 cars_com_scrapper